apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: repowarden
  name: repowarden-website
  labels:
    app: repowarden-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: repowarden-website
  template:
    metadata:
      labels:
        app: repowarden-website
    spec:
      containers:
      - name: website
        image: "ghcr.io/repowarden/www.repowarden.com:latest"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: repowarden
  name: repowarden-website
  labels:
    app: repowarden-website
spec:
  type: ClusterIP
  selector:
    app: repowarden-website
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: repowarden
  name: repowarden-website
  labels:
    app: repowarden-website
spec:
  ingressClassName: caddy
  rules:
  - host: www.repowarden.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: repowarden-website
            port:
              number: 80
  - host: repowarden.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: repowarden-website
            port:
              number: 80
